# Generated by Django 3.2.4 on 2022-01-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='img',
            field=models.ImageField(default=1, upload_to='product_img/', verbose_name=''),
            preserve_default=False,
        ),
    ]
